title: That's one hell of a pilot
author: Finn
email: FN-2187@traitor.First.Order.com
description: > # this means to ignore newlines until "baseurl:"
  This is about Finn, the next Jedi hero of the resistance
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
